# Use postgres/example user/password credentials
version: '3.5'

services:
  spp-node-1:
    container_name: ${SPP_CONTAINER_NAME}1
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=spp-node-1
      - NODE_IP=-1
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}/n1
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}/n1
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}/n1
        target: /sppnode/${LS_BASE_TEMP_DIR}
  spp-node-2:
    container_name: ${SPP_CONTAINER_NAME}2
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=spp-node-2
      - NODE_IP=-2
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}/n2
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}/n2
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}/n2
        target: /sppnode/${LS_BASE_TEMP_DIR}
  spp-node-3:
    container_name: ${SPP_CONTAINER_NAME}3
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=spp-node-3
      - NODE_IP=-3
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}/n3
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}/n3
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}/n3
        target: /sppnode/${LS_BASE_TEMP_DIR}
  spp-node-4:
    container_name: ${SPP_CONTAINER_NAME}4
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=spp-node-4
      - NODE_IP=-4
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}/n4
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}/n4
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}/n4
        target: /sppnode/${LS_BASE_TEMP_DIR}
  spp-node-5:
    container_name: ${SPP_CONTAINER_NAME}5
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=spp-node-5
      - NODE_IP=-5
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}/n5
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}/n5
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}/n5
        target: /sppnode/${LS_BASE_TEMP_DIR}
  spp-node-6:
    container_name: ${SPP_CONTAINER_NAME}6
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=spp-node-6
      - NODE_IP=-6
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}/n6
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}/n6
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}/n6
        target: /sppnode/${LS_BASE_TEMP_DIR}
  spp-node-7:
    container_name: ${SPP_CONTAINER_NAME}7
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=spp-node-7
      - NODE_IP=-7
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}/n7
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}/n7
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}/n7
        target: /sppnode/${LS_BASE_TEMP_DIR}
  spp-node-8:
    container_name: ${SPP_CONTAINER_NAME}8
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=spp-node-8
      - NODE_IP=-8
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}/n8
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}/n8
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}/n8
        target: /sppnode/${LS_BASE_TEMP_DIR}
  spp-node-9:
    container_name: ${SPP_CONTAINER_NAME}9
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=spp-node-9
      - NODE_IP=-9
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}/n9
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}/n9
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}/n9
        target: /sppnode/${LS_BASE_TEMP_DIR}
  spp-node-10:
    container_name: ${SPP_CONTAINER_NAME}10
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_NAME=spp-node-10
      - NODE_IP=-10
      - NODE_TYPES=SOURCE
    volumes:
      - type: bind # директория для логов
        source: ./${SPP_LOG_TEMP_PATH}/n10
        target: /sppnode/${SPP_LOG_TEMP_PATH}
      - type: bind # архив плагинов
        source: ./${PL_BASE_TEMP_DIR}/n10
        target: /sppnode/${PL_BASE_TEMP_DIR}
      - type: bind # локальное хранилище
        source: ./${LS_BASE_TEMP_DIR}/n10
        target: /sppnode/${LS_BASE_TEMP_DIR}
