# Use postgres/example user/password credentials
version: '3.5'

services:
  db-postgres:
    container_name: ${DB_CONTAINER_NAME}
    image: 'postgres:${DB_POSTGRES_VERSION}'
    restart: always
    ports:
      - "${DB_DOCKER_PORT}:5432"
    volumes:
      - type: bind
        source: ./scripts/${DB_BASE_TEMP_DIR}/init_and_create.sql
        target: ${DB_INIT_FILE}
        read_only: true
      - type: bind
        source: ./${DB_BASE_TEMP_DIR}/_data
        target: /var/lib/postgresql/_data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  ftp-server:
    container_name: ${FS_DOCKER_SERVICE_NAME}
    image: fauria/vsftpd
    restart: always
    environment:
      PASV_MAX_PORT: ${FS_PASV_MAX_PORT}
      PASV_MIN_PORT: ${FS_PASV_MIN_PORT}
      PASV_ADDRESS: ${FS_PASV_ADDRESS}
      FTP_PASS: ${FS_FTP_PASS}
      FTP_USER: ${FS_FTP_USER}
    volumes:
      - type: bind
        source: ./${FS_BASE_TEMP_DIR}
        target: /home/vsftpd/${FS_FTP_USER}
      - type: bind
        source: ./scripts/${FS_BASE_TEMP_DIR}/vsftpd.conf
        target: /home/vsftpd/vsftpd.conf
        read_only: true
    ports:
      - ${FS_PORT_20}:20
      - ${FS_PORT_21}:21
      - "${FS_PORTS_PASV}:21100-21110"