[tool.poetry]
name = "nspk-di-parser"
version = "0.1.0"
description = ""
authors = ["CuberHuber <romal5754@gmail.com>"]
readme = "README.md"
packages = [{ include = "nspk_di_parser" }]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.2"
selenium = "^4.8.2"
sqlalchemy = { extras = ["asyncio"], version = "^2.0.16" }
asyncpg = "^0.28.0"
alembic = "^1.11.1"
openpyxl = "^3.1.2"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
