[tool.poetry]
name = "nspk-di-parser"
version = "0.1.0"
description = ""
authors = ["CuberHuber <romal5754@gmail.com>"]
readme = "README.md"
packages = [{include = "nspk_di_parser"}]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^1.5.3"
selenium = "^4.8.2"
beautifulsoup4 = "^4.11.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
