name: Deploy to VPS

on:
#  push:
#    branches:
#      - main
#      - release/*
  release:
    types: [created, published]


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/NSPK-DI-Sources-Parser-Platform/
            sh init.sh
            git pull
            docker compose up -d --build
