name: Deploy to VPS

on:
  pull_request:
    branches:
      - "main"
      - "patch*"
    types:
      - closed

env:
  DOCKER_COMPOSE_FILE: 'docker-compose.yml'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/NSPK-DI-Sources-Parser-Platform/
            sh init.sh
            git pull
            docker compose -f ${{ DOCKER_COMPOSE_FILE }} up -d --build
